version: "3.8"
services:
  app:
    network_mode: host
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3333:3333"
    command: sh -c "yarn prisma:init && yarn start"
  postgres:
    network_mode: host
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  redis:
    network_mode: host
    image: redis
    ports:
      - "6379:6379"
