# GET all books
GET http://localhost:3333/book HTTP/1.1

# GET book by ID
GET http://localhost:3333/book/77 HTTP/1.1

# POST new book
POST http://localhost:3333/book HTTP/1.1
Content-Type: application/json

{
  "title": "The Fall",
  "author": "Albert Camus",
  "price": 7.99
}
